# This provides metadata for NIH-plug's `cargo xtask bundle <foo>` plugin
# bundler. This file's syntax is as follows:
#
# [package_name]
# name = "Human Readable Plugin Name"  # defaults to <package_name>

[audio_sampler]
name = "Audio Sampler"
extra-args = ""

# [pyo3_plugin]
# name = "PyO3 Plugin"

# [midi_sampler]
# name = "MIDI Sampler"