[package]
version = "0.1.0"
name = "audio_sampler_lib"
edition.workspace = true

[lib]
crate-type = ["lib", "staticlib"]

[build-dependencies]
cbindgen = "0.24.0"

[dependencies.smallvec]
version = "2.0.0-alpha.3"
